eci:
  security:
    jwt:
      audience: Econect
      claim:
        login: loginUsuario
        name: nomeUsuario
        roles: permissoes
      expirationTimeInMinutes: 120
      issuer: ECI-API-Issuer
      notBeforeThePastInMinutes: 10
      subject: ECI-API-JTW-Token
    rsa:
      private-key: classpath:eci-private.pem
      public-key: classpath:eci-public.pem

logging:
  level:
    br:
      econect:
        eci: INFO
    root: INFO

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  api-docs:
    path: /api-docs
  show-actuator: false
  swagger-ui:
    path: /api-docs-ui.html
