server:
  servlet:
    context-path: /eci-promocao

spring:
  application:
    name: eci-promocao-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: B4nc0my5q1
    url: jdbc:mysql://localhost:3306/eci_promocao?createDatabaseIfNotExist=true
    testWhileIdle: true
    validationQuery: SELECT 1

logging:
  level:
    br:
      econect:
        eci:
          promocao: DEBUG
