server:
    servlet:
        context-path: /eci-login
    port: 0

spring:
    application:
        name: eci-login-service
    main:
        allow-circular-references: true

logging:
    level:
        br:
            econect:
                eci:
                    login: INFO
        root: INFO

