spring:
  application:
    name: eci-discovery-service

server:
  port: 9081

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:9081/eureka
