spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: B4nc0my5q1
    url: jdbc:mysql://localhost:3306/eci_usuario?createDatabaseIfNotExist=true
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false

logging:
  level:
    br:
      econect:
        eci:
          usuario: INFO
    root: INFO
