spring:
    application:
        name: eci-login-service

spring:
  main:
    allow-circular-references: true

logging:
    level:
        br:
            econect:
                eci:
                    login: INFO
        root: INFO

