server:
    servlet:
        context-path: /eci-audit-operacao
    port: 0

spring:
    application:
        name: eci-audit-operacao-service
    data:
        mongodb:
            uri: mongodb://localhost:27017/eci_auditoper

logging:
    level:
        br:
            econect:
                eci:
                    auditoperacao: INFO
        root: INFO
