spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/eci_auditoper
      database: eci_auditoper
      auto-index-creation: true

logging:
  level:
    br:
      econect:
        eci:
          auditoperacao: INFO
    root: INFO
