server:
    port: 9595

logging:
    level:
        br:
            econect:
                eci:
                    gatewayservice: INFO
        root: INFO

spring:
    application:
        name: eci-gateway-service
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
        default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        globalcors:
            corsConfigurations:
                '[/**]':
                    allowedOrigins: "*"
                    allowedMethods: "*"
                    allowedHeaders: "*"
            routes:
                -   id: id-route-eci-login
                    uri: lb://eci-login-service
                    predicates:
                        - Path=/eci-login/**
                -   id: id-route-classifmerc
                    uri: lb://eci-classifmerc-service
                    predicates:
                        - Path=/eci-classifmerc/**
                -   id: id-route-preco
                    uri: lb://eci-preco-service
                    predicates:
                        - Path=/eci-preco/**
                -   id: id-route-produto
                    uri: lb://eci-produto-service
                    predicates:
                        - Path=/eci-produto/**
                -   id: id-route-promocao
                    uri: lb://eci-promocao-service
                    predicates:
                        - Path=/eci-promocao/**
                -   id: id-route-usuario
                    uri: lb://eci-usuario-service
                    predicates:
                        - Path=/eci-usuario/**
                -   id: id-route-cliente
                    uri: lb://eci-cliente-service
                    predicates:
                        - Path=/eci-cliente/**

